gui_project_job_limit: 1  # 1: GUI project can only run one job per user
                          # other value: no limit
data_home: $HOME/WORK
#data_home: /home/export/base/nsccwuxi_amd/$USER/WORK    # if defined, the project CWD will be
                          # data_home/project_name. The entire directory
                          # is removed after the project is deleted
instance_on_desk: false
forum: yes
title: 神工坊
watermark: img/simforge2.png
login_logo: img/simforge.png
op_control: '../apps'
job_size_list:
- 1
- 2
- 3
- 4
- 6
- 8
- 12
- 16
- 24
- 32
- 48
- 64
- 72
- 96
- 120
- 192
app_access:
  PointWise:
  - simforge6
  - simforge2
  - amd_app
  电子散热仿真App:
  - simforge6
  FluentMesh2020:
  - amd_app
  CFD-POST2020:
  - amd_app
  - simforge6
  - sim_xqy
  CFX-pre2020:
  - amd_app
  - simforge6
  - sim_xqy
  CFX2020:
  - amd_app
  - simforge6
  - sim_xqy
#
#download:
#- name: Windows文件压缩工具
#  url: http://dl.2345.com/haozip/2345haozip_v6.1.0.11022.exe
#licenses:
#- server: '1700@linux7'
#  features:
#    - acfd
#    - anshpc_pack
#lmstat: /var/www/html/cmd/lmstat
